source 'http://rubygems.org'
gem 'sinatra'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'bcrypt-ruby'

group :development, :test do
	gem 'capybara'
	gem 'cucumber'
	gem 'cucumber-sinatra'
	gem 'database_cleaner'
	gem 'rspec'
	gem 'shotgun'
end
