source 'http://rubygems.org'
gem 'sinatra'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'bcrypt-ruby'
gem 'rack-flash3', '~> 1.0.5'

group :development, :test do
	gem 'capybara'
	gem 'cucumber'
	gem 'cucumber-sinatra'
	gem 'database_cleaner'
	gem 'rspec'
	gem 'shotgun'
end
